// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {updater} from '../models';
import {deps} from '../models';

export function AddToQueue(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean,arg6:domain.PlaylistSelection,arg7:domain.Cookies):Promise<string>;

export function CheckAppUpdate():Promise<updater.UpdateResult>;

export function CheckDependencies():Promise<Array<deps.DependencyState>>;

export function DownloadAppUpdate(arg1:string):Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetDefaultDownloadPath():Promise<string>;

export function GetMediaDefaults():Promise<domain.MediaDefaults>;

export function GetQueue():Promise<Array<domain.Media>>;

export function GetSettings():Promise<domain.Setting>;

export function GetSupportedBrowsersForCookies():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function LaunchInstaller(arg1:string):Promise<void>;

export function PauseDownloads():Promise<void>;

export function PauseSingleDownload(arg1:string):Promise<void>;

export function PerformFullUpdate():Promise<Record<string, any>>;

export function RemoveFromQueue(arg1:string):Promise<void>;

export function SaveMediaDefaults():Promise<void>;

export function SaveSettings():Promise<void>;

export function SelectCookiesPath(arg1:string):Promise<string>;

export function SelectDownloadFolder():Promise<string>;

export function SelectDownloadFolderWithDefault(arg1:string):Promise<string>;

export function SetupDependencies():Promise<void>;

export function ShowInFolder(arg1:string):Promise<void>;

export function ShutDown():Promise<void>;

export function StartDownloads():Promise<void>;

export function StartSingleDownload(arg1:string):Promise<void>;

export function UpdateMediaDefaults(arg1:string,arg2:string,arg3:boolean,arg4:domain.Cookies):Promise<void>;

export function UpdateSettings(arg1:number):Promise<void>;
