// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToQueue(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['AddToQueue'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function CheckAppUpdate() {
  return window['go']['main']['App']['CheckAppUpdate']();
}

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function DownloadAppUpdate(arg1) {
  return window['go']['main']['App']['DownloadAppUpdate'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetDefaultDownloadPath() {
  return window['go']['main']['App']['GetDefaultDownloadPath']();
}

export function GetMediaDefaults() {
  return window['go']['main']['App']['GetMediaDefaults']();
}

export function GetQueue() {
  return window['go']['main']['App']['GetQueue']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSupportedBrowsersForCookies() {
  return window['go']['main']['App']['GetSupportedBrowsersForCookies']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LaunchInstaller(arg1) {
  return window['go']['main']['App']['LaunchInstaller'](arg1);
}

export function PauseDownloads() {
  return window['go']['main']['App']['PauseDownloads']();
}

export function PauseSingleDownload(arg1) {
  return window['go']['main']['App']['PauseSingleDownload'](arg1);
}

export function PerformFullUpdate() {
  return window['go']['main']['App']['PerformFullUpdate']();
}

export function RemoveFromQueue(arg1) {
  return window['go']['main']['App']['RemoveFromQueue'](arg1);
}

export function SaveMediaDefaults() {
  return window['go']['main']['App']['SaveMediaDefaults']();
}

export function SaveSettings() {
  return window['go']['main']['App']['SaveSettings']();
}

export function SelectCookiesPath(arg1) {
  return window['go']['main']['App']['SelectCookiesPath'](arg1);
}

export function SelectDownloadFolderWithDefault(arg1) {
  return window['go']['main']['App']['SelectDownloadFolderWithDefault'](arg1);
}

export function SetupDependencies() {
  return window['go']['main']['App']['SetupDependencies']();
}

export function ShowInFolder(arg1) {
  return window['go']['main']['App']['ShowInFolder'](arg1);
}

export function ShutDown() {
  return window['go']['main']['App']['ShutDown']();
}

export function StartDownloads() {
  return window['go']['main']['App']['StartDownloads']();
}

export function StartSingleDownload(arg1) {
  return window['go']['main']['App']['StartSingleDownload'](arg1);
}

export function UpdateMediaDefaults(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateMediaDefaults'](arg1, arg2, arg3, arg4);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
